## Numpy Arrays

In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4,5])
a

array([2, 3, 4, 5])

In [3]:
c = np.array([2,3,4,5,6,2]).reshape(2,3) # Creates a table out of the array 
c

array([[2, 3, 4],
       [5, 6, 2]])

In [4]:
d = np.array([2,3,4,5,6,2,3,4]).reshape(2,2,2)
d

array([[[2, 3],
        [4, 5]],

       [[6, 2],
        [3, 4]]])

### Numpy Calculations 

In [5]:
e = np.array([1,2,3,4,5,6])
print(e.sum())
print(e.min())
print(e.max())
print(e.mean())


21
1
6
3.5


### Special Numpy Arrays

In [6]:
zeroarray = print(np.zeros(5)) # Creates sn srrsay of all zeros with 5 elements 
print()

linespace = print(np.linspace(0,6,10)) # Creates an array of values from 0 through 6 in 10 even spaces
print()
random_values = print(np.random.rand(3)) # Three random values between 0 and 1
print()

random_int = print(np.random.randint(1,1000)) # A random integer between 1 and 1000
print()

numpy_range = print(np.arange(25)) # Like the Range function, this gibves you a range of integers berween 1 and 25
print()


[0. 0. 0. 0. 0.]

[0.         0.66666667 1.33333333 2.         2.66666667 3.33333333
 4.         4.66666667 5.33333333 6.        ]

[0.1212539  0.41819432 0.13706502]

829

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

